
Default:
    Active: True
    Language: en_US.UTF-8
    Keyboard: us
    PackageArgs:
    SaveRepos:  True
    Timezone: America/Toronto
    RootPass: meego
    DefaultUser: meego
    DefaultUserPass: meego
    PartSize: 1900
    FileSystem: ext3
    PostScripts:
        - rpm
    Groups:
        - MeeGo Core
        - MeeGo Compliance
    ExtraPackages:
        - libICE
        - libSM
        - libX11
        - libXau
        - libXaw
        - libXcomposite
        - libXcursor
        - libXdamage
        - libXdmcp
        - libXext
        - libXfixes
        - libXfont
        - libXft
        - libXi
        - libXinerama
        - libXmu
        - libXpm
        - libXrandr
        - libXrender
        - libXt
        - libXtst
        - libXv
        - libXxf86vm


CORE:
    PartSize: 1000
    BootloaderTimeout: 30
    PostScripts:
        - cleanup
    Groups:
        - MeeGo X Window System
    NoChrootScripts:
        - buildname
MOUI:
    PartSize: 2200
    Bootloader: True
    BootloaderTimeout: 30
    Session: "/usr/bin/xfce4-session"
    StartX: True
    Groups:
        - MeeGo Tablet
    Kernel: kernel-adaptation-pinetrail
    PostScripts:
        - prelink
        - cleanup
    NoChrootScripts:
        - buildname
    Architecture: ia32
    
Configurations:
    -   Name: MOUI Development
        Active: True
        Baseline: "1.2.0"
        Platform: MOUI
        Desktop: xfdesktop
        FileName: moui-devel-ia32
        Mic2Options: -f livecd
        Groups:
            - MeeGo Base Development
            - MeeGo Tablet Applications
            - Development Tools
        Repos:
            - oss
            - non-oss
            - devel-xfce
            - berndhs
            - berndhs-deploy
        ExtraPackages:
            - instalateur
            - Terminal
            - Thunar
            - exo
            - garcon
            - gigolo
            - gtk-xfce-engine
            - libnotify1
            - libwnck1
            - libxfce4ui
            - libxfce4util
            - libxfcegui4
            - mousepad
            - orage
            -  ristretto
            - squeeze
            - vte
            - xfce-utils
            - xfce4-appfinder
            - xfce4-battery-plugin
            - xfce4-mixer
            - xfce4-panel
            - xfce4-session
            - xfce4-settings
            - xfce4-taskmanager
            - xfconf
            - xfdesktop
            - xfwm4
            - burid
            - deeptrim
            - egalite
    -   Name: MOUI
        Active: True
        Baseline: "1.2.0"
        Platform: MOUI
        Desktop: xfdesktop
        FileName: moui-ia32
        Mic2Options: -f livecd
        Groups:
            - MeeGo Base Development
            - MeeGo Tablet Applications
        Repos:
            - oss
            - non-oss
            - devel-xfce
            - berndhs
            - berndhs-deploy
        ExtraPackages:
            - installer
            - installer-shell-b
            - Terminal
            - Thunar
            - exo
            - garcon
            - gigolo
            - gtk-xfce-engine
            - libnotify1
            - libwnck1
            - libxfce4ui
            - libxfce4util
            - libxfcegui4
            - mousepad
            - orage
            -  ristretto
            - squeeze
            - vte
            - xfce-utils
            - xfce4-appfinder
            - xfce4-battery-plugin
            - xfce4-mixer
            - xfce4-panel
            - xfce4-session
            - xfce4-settings
            - xfce4-taskmanager
            - xfconf
            - xfdesktop
            - xfwm4
            - burid
            - deeptrim
            - egalite
