
Default:
    Active: True
    Language: en_US.UTF-8
    Keyboard: us
    SaveRepos:  True
    Timezone: America/Toronto
    RootPass: meego
    DefaultUser: meego
    DefaultUserPass: meego
    PartSize: 1900
    FileSystem: ext3
    PostScripts:
        - rpm
    Groups:
        - MeeGo Core
        - MeeGo Compliance
        - Minimal MeeGo X Window System
    ExtraPackages:
        - instalateur
        - vim-enhanced
        - vim-X11
        - zypper
        - sudo
        - openssh
        - openssh-clients
        - openssh-server


MOUI:
    PartSize: 2200
    Bootloader: True
    BootloaderTimeout: 30
    Session: "/usr/bin/mcompositor"
    StartX: True
    Groups:
        - MeeGo Tablet
    Kernel: kernel
    PostScripts:
        - prelink
        - cleanup
    NoChrootScripts:
        - buildname
    Architecture: ia32
    Repos:
          - 1.2-oss
          - 1.2-non-oss
          - devel-xfce
          - berndhs
          - berndhs-deploy
    
Configurations:
    -   Name: MOUI Development
        Active: True
        Baseline: "1.2.0"
        Platform: MOUI
        Desktop: X-DUI
        FileName: moui-devel-ia32
        Mic2Options: -f livecd
        Groups:
            - MeeGo Base Development
            - MeeGo Tablet Applications
            - Development Tools

    -   Name: MOUI
        Active: True
        Baseline: "1.2.0"
        Platform: MOUI
        Desktop: X-DUI
        FileName: moui-ia32
        Mic2Options: -f livecd

