ExternalConfigs: 
    - ex
Default:
    Active: True
    Language: en_US.UTF-8
    Keyboard: us
    PackageArgs:
    SaveRepos:  True
    Timezone: America/Toronto
    RootPass: meego
    DefaultUser: meego
    DefaultUserPass: meego
    PartSize: 1900
    FileSystem: ext3
    PostScripts:
        - rpm
    Groups:
        - MeeGo Core
        - MeeGo Compliance

CORE:
    PartSize: 1000
    BootloaderAppend: "quiet"
    BootloaderTimeout: 30
    PostScripts:
        - cleanup
    Groups:
        - MeeGo X Window System
    NoChrootScripts:
        - buildname
MOUI:
    PartSize: 2200
    Bootloader: True
    BootloaderAppend: "quiet"
    BootloaderTimeout: 0
    Session: "/usr/bin/startx"
    StartX: True
    Groups:
        - X for Tablet
    Kernel: kernel-adaptation-intel-automotive
    PostScripts:
        - prelink
        - cleanup
    NoChrootScripts:
        - buildname
    Architecture: ia32
    
Configurations:
    -   Name: MOUI Development
        Active: True
        Baseline: "1.2.0.90"
        Platform: MOUI
        Desktop: X-Tablet
        FileName: moui-devel-ia32
        Mic2Options: -f livecd
        Groups:
            - MeeGo Tablet Desktop
            - MeeGo Base Development
            - MeeGo Tablet Applications
            - Development Tools
        Repos:
            - oss
            - non-oss
    -   Name: MOUI
        Active: True
        Baseline: "1.2.0.90"
        Platform: MOUI
        Desktop: X-Tablet
        FileName: moui-ia32
        Mic2Options: -f livecd
        Groups:
            - MeeGo Tablet Desktop
            - MeeGo Base Development
            - MeeGo Tablet Applications
        Repos:
            - oss
            - non-oss
